For reliability testing

diff --git a/.github/workflows/destroy.yaml b/.github/workflows/destroy.yaml
--- a/.github/workflows/destroy.yaml
+++ b/.github/workflows/destroy.yaml
@@ -1,90 +1,87 @@
 name: Destroy Infrastructure
 
 on:
-  push:
-    branches:
-      - main
   workflow_dispatch:
 
 jobs:
-  # destroy-cluster:
-  #   runs-on: self-hosted
-  #   permissions:
-  #     contents: write
-  #   steps:
-  #   - name: Checkout this Github repository
-  #     uses: actions/checkout@v4
-  #   - name: Install doctl
-  #     uses: digitalocean/action-doctl@v2
-  #     with:
-  #       token: ${{ secrets.DO_API_TOKEN }}
-  #   - name: Move /deploy contents to /terraform
-  #     run: |
-  #       mv deploy/* .
-  #     working-directory: ./terraform
-  #   - name: Setup Terraform
-  #     uses: hashicorp/setup-terraform@v3
-  #     with:
-  #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-  #   - name: Cache Terraform Plugin Dir
-  #     uses: actions/cache@v3
-  #     with:
-  #       path: ~/.terraform.d/plugin-cache
-  #       key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
-  #       restore-keys: |
-  #         terraform-plugin-cache-${{ runner.os }}-
-  #   - name: Destory DOKS Terraform Resources
-  #     env:
-  #       TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
-  #       DIGITALOCEAN_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
-  #       RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
-  #       CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
-  #       CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
-  #     run: |
-  #       set -e
+  destroy-cluster:
+    runs-on: self-hosted
+    permissions:
+      contents: write
+    steps:
+    - name: Checkout this Github repository
+      uses: actions/checkout@v4
+    - name: Install doctl
+      uses: digitalocean/action-doctl@v2
+      with:
+        token: ${{ secrets.DO_API_TOKEN }}
+    - name: Move /deploy contents to /terraform
+      run: |
+        mv deploy/* .
+      working-directory: ./terraform
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v3
+      with:
+          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+    - name: Cache Terraform Plugin Dir
+      uses: actions/cache@v3
+      with:
+        path: ~/.terraform.d/plugin-cache
+        key: terraform-plugin-cache-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
+        restore-keys: |
+          terraform-plugin-cache-${{ runner.os }}-
+    - name: Destory DOKS Terraform Resources
+      env:
+        TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
+        DIGITALOCEAN_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
+        RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
+        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
+        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+      run: |
+        set -e
 
-  #       echo "Initializing and validating Terraform configuration"
-  #       terraform init
-  #       terraform validate
+        echo "Initializing and validating Terraform configuration"
+        terraform init
+        terraform validate
 
-  #       cat <<EOF > terraform.tfvars.json
-  #       {
-  #         "github_runner_token": "$RUNNER_TOKEN",
-  #         "do_token": "$DIGITALOCEAN_API_TOKEN",
-  #         "cloudflare_api_token": "$CLOUDFLARE_TOKEN",
-  #         "cloudflare_zone_id": "$CLOUDFLARE_ZONE_ID"
-  #       }
-  #       EOF
+        cat <<EOF > terraform.tfvars.json
+        {
+          "github_runner_token": "$RUNNER_TOKEN",
+          "do_token": "$DIGITALOCEAN_API_TOKEN",
+          "cloudflare_api_token": "$CLOUDFLARE_TOKEN",
+          "cloudflare_zone_id": "$CLOUDFLARE_ZONE_ID"
+        }
+        EOF
 
-  #       echo "Configuring Terraform to use plugin cache"
-  #       mkdir -p ~/.terraform.d/plugin-cache
-  #       echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
+        echo "Configuring Terraform to use plugin cache"
+        mkdir -p ~/.terraform.d/plugin-cache
+        echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
 
-  #       echo "Attempting to destroy DOKS cluster (max 3 attempts)..."
-  #       for destroy in {1..3}; do
-  #         echo "Attempt $destroy..."
-  #         terraform destroy -target=digitalocean_kubernetes_cluster.kronos --auto-approve && break || {
-  #           echo "Terraform destroy failed (attempt $destroy)."
-  #           if [ "$destroy" -lt 3 ]; then
-  #             echo "Retrying in 10 seconds..."
-  #             sleep 10
-  #           else
-  #             echo "All attempts failed..."
-  #             exit 1
-  #           fi
-  #         }
-  #       done
-  #     working-directory: ./terraform
-  #   - name: Commit Terraform Lock File
-  #     uses: stefanzweifel/git-auto-commit-action@v5
-  #     with:
-  #       commit_message: "chore: update terraform.lock.hcl"
-  #       file_pattern: "terraform/.terraform.lock.hcl"
-  #       commit_user_name: "github-actions[bot]"
-  #       commit_user_email: "github-actions[bot]@users.noreply.github.com"
+        echo "Attempting to destroy DOKS cluster (max 3 attempts)..."
+        for destroy in {1..3}; do
+          echo "Attempt $destroy..."
+          terraform destroy -target=digitalocean_kubernetes_cluster.kronos --auto-approve && break || {
+            echo "Terraform destroy failed (attempt $destroy)."
+            if [ "$destroy" -lt 3 ]; then
+              echo "Retrying in 10 seconds..."
+              sleep 10
+            else
+              echo "All attempts failed..."
+              exit 1
+            fi
+          }
+        done
+      working-directory: ./terraform
+    - name: Commit Terraform Lock File
+      uses: stefanzweifel/git-auto-commit-action@v5
+      with:
+        commit_message: "chore: update terraform.lock.hcl"
+        file_pattern: "terraform/.terraform.lock.hcl"
+        commit_user_name: "github-actions[bot]"
+        commit_user_email: "github-actions[bot]@users.noreply.github.com"
     
   destroy-runner-vm:
-    # needs: destroy-cluster
+    needs: destroy-cluster
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -133,7 +130,11 @@ jobs:
         }
         EOF
 
-        terraform destroy --auto-approve
+        terraform destroy -target=digitalocean_droplet.kronos --auto-approve
+        terraform destroy -target=digitalocean_firewall.kronos --auto-approve
+        terraform destroy -target=digitalocean_firewall.kronos_bastion --auto-approve
+        terraform destroy -target=digitalocean_tag.kronos --auto-approve
+        terraform destroy -target=digitalocean_vpc_nat_gateway.kronos --auto-approve
       working-directory: ./terraform
     - name: Commit Terraform Lock File
       uses: stefanzweifel/git-auto-commit-action@v5
