enable metrics and emit ingress spans

diff --git a/.github/workflows/destroy.yaml b/.github/workflows/destroy.yaml
--- a/.github/workflows/destroy.yaml
+++ b/.github/workflows/destroy.yaml
@@ -101,8 +101,11 @@ jobs:
         CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
         CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
       run: |
-        mkdir -p ~/.terraform.d/plugin-cache
-        echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
+        set -e
+
+        echo "Initializing and validating Terraform configuration"
+        terraform init
+        terraform validate
 
         cat <<EOF > terraform.tfvars.json
         {
@@ -113,11 +116,24 @@ jobs:
         }
         EOF
 
-        terraform init
-        terraform providers
-        terraform validate
+        echo "Configuring Terraform to use plugin cache"
+        mkdir -p ~/.terraform.d/plugin-cache
+        echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc
 
-        terraform destroy --auto-approve
+        echo "Attempting to destroy Droplet (max 3 attempts)..."
+        for destroy in {1..3}; do
+          echo "Attempt $destroy..."
+          terraform destroy --auto-approve && break || {
+            echo "Terraform destroy failed (attempt $destroy)."
+            if [ "$destroy" -lt 3 ]; then
+              echo "Retrying in 10 seconds..."
+              sleep 10
+            else
+              echo "All attempts failed..."
+              exit 1
+            fi
+          }
+        done
       working-directory: ./terraform
     - name: Commit Terraform Lock File
       uses: stefanzweifel/git-auto-commit-action@v5
